### ISSUE TITLE
Disqus integration

### ISSUE THREAD

**Issue by jonas** [sbt/sbt-paradox-material-theme#2]
From https://squidfunk.github.io/mkdocs-material/getting-started/#disqus-integation

Partial: https://github.com/squidfunk/mkdocs-material/blob/master/src/partials/disqus.html

**Comment by mkurz** [comment]
I am closing this for now, because Disqus integation was removed:
https://squidfunk.github.io/mkdocs-material/changelog/#8.0.0
> - Removed Disqus integation – use customization
