### ISSUE TITLE
How to use it in projects built with Maven

### ISSUE THREAD

**Issue by GeTOUO** [sbt/sbt-paradox-material-theme#23]
How to use it in projects built with Maven？

My project used Scala built by maven. I wanted to use this library to generate documents, but I didn't find a case in maven.

**Comment by GeTOUO** [comment]
hello？

**Comment by mkurz** [comment]
This is an sbt plugin, so this will not work with Maven (at least not in a way that you can just add some configs within a couple of minutes and boom, it works)
