### ISSUE TITLE
Most libraries out of date

### ISSUE THREAD

**Issue by jwgcooke** [sbt/sbt-paradox-material-theme#33]
Is this project still maintained/used?  I have another project that has a dependency here and I am happy to put together a PR to update everything but as it stands including this causes a bunch of dependency conflicts.

**Out Of date plugins:** 
paradox (0.4.4 --> 0.10.2)
sbt-site (1.3.2 --> 1.4.1) 
sbt-ghpages (0.6.2 --> 0.6.3)

**Out of Date Libraries**
circe-core (0.8.0 --> 0.14.3)
jsoup (1.10.3 --> 1.15.3)

**Comment by mkurz** [comment]
main branch is more or less up to date. We will cut new releases soon.
